Spotipy backend
masonmcelvain/geomusic pull request #25
Opened 2021-05-20 03:21 UTC by nbehmane

Changed how we were storing user data and integrated spotipy.

2021-05-20 03:22 UTC, nbehmane commented
Failing travis since I didn't include sensitive data in the github

2021-05-22 16:52 UTC, masonmcelvain approved these changes
Nice work! Minor comment about a commented out code block, but this all looks good to me

2021-05-22 16:52 UTC, masonmcelvain commented on playlist.py
> +"""
Are we commenting this out so you can save it for later? We could just delete it to reduce clutter. Seems like you could just go back in version control and get this if you needed it in the future.

2021-05-29 19:34 UTC, scole02 commented
Looks good to me

2021-06-01 19:19 UTC, masonmcelvain requested changes
Nice job! This is solid. A few minor comments, mostly around documentation / styling

2021-06-01 19:19 UTC, masonmcelvain commented on .travis.yml
> +  - pip install pytest
if our requirements.txt is up to date, we could just list `pip install -r requirements.txt` and remove the rest of these

2021-06-01 19:19 UTC, masonmcelvain commented on README.md
>  ## Database
We should delete the parts of the README that aren't associated with the backend (ie Database, Frontend parts)

2021-06-01 19:19 UTC, masonmcelvain commented on app.py
> +            ]
indentation is funky

2021-06-01 19:19 UTC, masonmcelvain commented on app.py
> +                       ((playlist['location'][1] - data['location'][1]) ** 2))
this is dense. maybe we could extract this out into it's own function with a descriptive name

2021-06-01 19:19 UTC, masonmcelvain commented on backend_tests.py
> +        and adding that user to our database'''
is this still a valid TODO, or can it be deleted?

2021-06-01 19:19 UTC, masonmcelvain commented on backend_tests.py
> +            ]
indentation

2021-06-01 19:20 UTC, masonmcelvain commented
We'll also need to settle the merge conflict once the README is ready to go.

2021-06-01 19:21 UTC, nbehmane commented on .travis.yml
> +  - pip install pytest
For sure, I'll make sure remove those from the README and just include it in requirements.txt

2021-06-01 19:23 UTC, nbehmane commented on README.md
>  ## Database
For sure, I think the database steps should be there just for the backend as a whole to work properly. Do you think I should still get rid of it in the readme?

2021-06-01 19:23 UTC, nbehmane commented on app.py
> +            ]
Will fix those indentation issues.

2021-06-01 19:23 UTC, nbehmane commented on app.py
> +                       ((playlist['location'][1] - data['location'][1]) ** 2))
I agree with you, that should be refactored out of there. I'll update the code and push the changes.

2021-06-01 19:23 UTC, nbehmane commented on backend_tests.py
> +        and adding that user to our database'''
These are not valid TODO's anymore, will get rid of them in the code. Thanks for pointing that out.

2021-06-01 19:32 UTC, masonmcelvain commented on README.md
>  ## Database
Oh, yea keep the database stuff sorry!

2021-06-02 03:42 UTC, masonmcelvain approved these changes
Nice, thanks!

2021-06-02 03:42 UTC, merged

2021-06-02 03:55 UTC, kylene-phillips reviewed
Great changes and important additions. Thanks for making the sensitive data hidden now. Been working with the backend and your code does everything except update the images in the backend which we need. We will work on that together

2021-06-02 03:56 UTC, kylene-phillips reviewed
Looks good, thank you!