Frontend: Homescreen updates, custom Carousel component
masonmcelvain/geomusic pull request #26
Opened 2021-05-21 19:49 UTC by scole02

Updated homescreen to resemble figma mockup using [Carousel component](https://github.com/rossbulat/rn-carousel/tree/master/Carousel):  
<div/>
<div/>

![image](https://user-images.githubusercontent.com/50273323/119190514-53ae6000-ba32-11eb-8c85-b1af2c1f172c.png)
*Figma Mockup*  
<div/>  

![image](https://user-images.githubusercontent.com/50273323/119190874-c28bb900-ba32-11eb-847c-3bc4839296a2.png)
*actual homescreen on android*

2021-05-22 16:16 UTC, masonmcelvain commented
I fixed the merge conflicts, so after we all give our review, your code will be able to be merged into `frontend`

2021-05-22 16:25 UTC, masonmcelvain commented
<img width="404" alt="Screen Shot 2021-05-22 at 9 22 23 AM" src="https://user-images.githubusercontent.com/52104630/119233739-44d1b700-badf-11eb-999d-ae5712e3ed39.png">

It would be cool if we could use a dark theme like the rest of the app. In the future, it would be nice to give the user the choice of whether to use a light or dark theme, but we will just stick with dark theme for consistency now.

2021-05-22 16:35 UTC, masonmcelvain requested changes
This is really good, nice work! I requested a few changes, but the UI itself looks solid besides my notes about the color

2021-05-22 16:35 UTC, masonmcelvain commented on screens/HomeScreen.tsx
> +    shadowColor: "#fcfcfc",
It would be nice if we could use the predefined styles from the `constants/Colors.ts` file instead of defining our own here

2021-05-22 16:35 UTC, masonmcelvain commented on screens/HomeScreen.tsx
> +            navigator: navigation,
Why do we need to include a navigator in each item? The navigator is the same as that passed to the Carousel component above. Seems redundant.

2021-05-22 16:35 UTC, masonmcelvain commented on screens/HomeScreen.tsx
> +            navigator: navigation,
Instead of just using the same playlist 3 times, lets define a new array of `recentPlaylists` with useState. Then, we can just map that array into this `items` prop. We can get rid of the `playlist` useState altogether, that was just a standin before.

This approach is better because eventually we'll need to make an API call to get the playlist data from the backend, and we'll probably get it as an array of playlists.

Same goes for 'playlists near you' below.

2021-05-26 16:15 UTC, scole02 commented on screens/HomeScreen.tsx
> +            navigator: navigation,
Agreed

2021-05-26 16:15 UTC, merged

2021-06-02 03:50 UTC, kylene-phillips commented on screens/HomeScreen.tsx
> +            navigator: navigation,
The carousel works well for both iOS and Android and I like how it works with the navigation we already have working